# Generated by Django 5.1.8 on 2025-05-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False, max_length=24, primary_key=True, serialize=False
                    ),
                ),
                ("username", models.CharField(max_length=150)),
                ("password", models.CharField(max_length=128)),
                ("rePassword", models.CharField(max_length=128)),
                ("email", models.EmailField(max_length=254)),
                ("firstName", models.CharField(max_length=150)),
                ("lastName", models.CharField(max_length=150)),
                ("phoneNumber", models.CharField(max_length=20)),
                ("premiumDate", models.DateTimeField()),
                ("createdDate", models.DateTimeField()),
                ("deleteFlag", models.BooleanField(default=False)),
            ],
        ),
    ]
