# Generated by Django 5.1.8 on 2025-09-06 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="rePassword",
        ),
    ]
