# Generated by Django 5.1.8 on 2025-05-05 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.CharField(editable=False, max_length=24, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('genre', models.JSONField()),
                ('composer', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('level', models.CharField(choices=[(1, 'مبتدی'), (2, 'متوسط'), (3, 'پیشرفته')], max_length=1)),
                ('rate', models.FloatField()),
                ('likes', models.IntegerField()),
                ('voters', models.IntegerField()),
                ('views', models.IntegerField()),
                ('createdAt', models.DateTimeField()),
                ('deleteFlag', models.BooleanField(default=False)),
                ('comments', models.JSONField(default=list)),
                ('notesheet', models.FileField(blank=True, null=True, upload_to='notesheets/')),
                ('preview', models.FileField(blank=True, null=True, upload_to='notesheets/previews/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
