# Generated by Django 5.1.8 on 2025-05-05 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.CharField(editable=False, max_length=24, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('genre', models.JSONField()),
                ('description', models.TextField(blank=True, null=True)),
                ('level', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('createdAt', models.DateTimeField()),
                ('deleteFlag', models.BooleanField(default=False)),
                ('comments', models.JSONField(default=list)),
                ('notesheet', models.FileField(blank=True, null=True, upload_to='notesheets/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
