# Generated by Django 5.1.8 on 2025-05-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='notesheets/previews/'),
        ),
    ]
