# Generated by Django 5.1.8 on 2025-05-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_note_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='level',
            field=models.IntegerField(choices=[(1, 'مبتدی'), (2, 'متوسط'), (3, 'پیشرفته')]),
        ),
    ]
