# Generated by Django 5.1.8 on 2025-08-19 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="excercise",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False, max_length=24, primary_key=True, serialize=False
                    ),
                ),
                ("metrics", models.JSONField(default=list)),
                (
                    "audio",
                    models.CharField(
                        blank=True,
                        help_text="Path to user's audio file (e.g. 'userId_filename.wav')",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "ref_audio",
                    models.CharField(
                        blank=True,
                        help_text="Path to reference audio file (e.g. 'ref_audio_name')",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "userId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
