# Generated by Django 5.1.8 on 2025-09-15 07:37

import auctions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_alter_auction_seller_alter_bid_bidder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="id",
            field=models.CharField(
                default=auctions.models.make_objectid_hex,
                editable=False,
                max_length=24,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="bid",
            name="id",
            field=models.CharField(
                default=auctions.models.make_objectid_hex,
                editable=False,
                max_length=24,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
